### ISSUE TITLE
Pixlet Sample clock does not update time

### ISSUE THREAD

**Issue by joxtraex** [tidbyt/pixlet#115]
I am testing out writing an application and just following the tutorial which involves having text as a simple clock.  After having pushed the binary to the device, I would expect the clock would update with realworld time.. but it does not. The time stays constant and never changes.

Sample code:
```
load("render.star", "render")
load("time.star", "time")

def main(config):
    timezone = config.get("timezone") or "America/Los_Angeles"
    print("Timezone: :"+str(timezone))
    now = time.now().in_location(timezone)

    return render.Root(
        delay = 500,
        child = render.Box(
            child = render.Animation(
                children = [
                    render.Text(
                        content = now.format("3:04 PM"),
                        font = "6x13",
                    ),
                    render.Text(
                        content = now.format("3 04 PM"),
                        font = "6x13",
                    ),
                ],
            ),
        ),
    )
```
To my understanding the render delay should be redrawing the text with the time variable, which I do see the ":" being updated accordingly but the time never updates. Could you please tell me if I am missing something?   
   
Also could you please provide the source code to the applications on the device just for reference? And if there any limitations between applications already present on the device vs applications pushed remotely?

Please let me know if you need more information.

Thanks.

**Comment by joeyhoer** [comment]
@joxtraex This is how `pixlet` operates; `pixlet` if effectively a tool to generate static `webp` images. If you want to update the time again, you need to render a new `webp` with `pixlet` and then push it to your Tidbyt.

If you'd like more information, you might want to read through this thread: https://github.com/tidbyt/pixlet/issues/89

**Comment by joxtraex** [comment]
Gotcha that helps clarify how the webp works. Thank you for the link. So if I am understanding correctly the way you achieve this with the other apps is through a webservice endpoint that it pings periodically. Is that right?
