### ISSUE TITLE
--watch flag not working

### ISSUE THREAD

**Issue by mackorone** [tidbyt/pixlet#16]
The `--watch` flag isn't working on my machine (Ubuntu 16.04 LTS). Here's the command I'm running:
```
pixlet serve --watch nyan_cat.star
```
Here's the output:
```
Loaded tidbyt-nyan-cat/nyan_cat.star, watching for changes
listening on tcp/8080
```
Whenever I update the `nyan_cat.star` file, I have to restart `pixlet` *and* refresh the webpage to see the changes. Isn't the `--watch` flag supposed to eliminate need to restart `pixlet`?

**Comment by rohansingh** [comment]
> Whenever I update the nyan_cat.star file, I have to restart pixlet and refresh the webpage to see the changes. Isn't the --watch flag supposed to eliminate need to restart pixlet?

Yes, it is. Looking into this.

**Comment by matslina** [comment]
Seems to have been a vim specific issue. #24 hopefully fixes it.
