### ISSUE TITLE
Question: Is there a way to push to Tidbyt hardware outside Tidbyt's servers?

### ISSUE THREAD

**Issue by balanceiskey** [tidbyt/pixlet#179]
Apologies if this is the wrong forum to ask this question in (and please redirect me if there's somewhere better): 

Is there a mechanism to push directly to the Tidbyt on a local network without interacting with Tidbyt's servers? 

Why: In scenarios where we might be testing or potentially have sensitive information to display, it would be nice if devs could interact with the device without it necessarily reaching back to Tidbyt. In the most aggressive scenario, I'd really love a way to completely split the hardware from Tidbyt's servers to provide complete security when it's sitting and running and instead use a local server inside the house to push content.

**Comment by drudge** [comment]
Hi @balanceiskey!

See this response from @rohansingh on the Community forums:

> The default Tidbyt experience does depend on our servers, and we haven’t open sourced our entire backend.
> 
> The device itself is bootloader-unlocked so you can flash your own firmware that serves [Pixlet 32](https://github.com/tidbyt/pixlet) apps from your own server. In doing that though you would lose out on or have to reimplement a fair bit of functionality, like being able to manage the device with a mobile app.
> 
> I could see a future in which we have a standalone version of the Tidbyt backend that you can run on your server or premises, but that’s not on the current roadmap.


https://discuss.tidbyt.com/t/self-hosted-tidbyt-server/330/2

**Comment by balanceiskey** [comment]
This helps @drudge! I'm going to close this out, this was mostly what I was looking for at this stage, thanks!

**Comment by khromov** [comment]
Just wanted to chime in that the cloud connectivity is an absolute no-go for me and likely many others. Preferably the Tidbyt should be able to run scripts on its own, but if that's not possible at least it should be able to receive data pushed to it on the local network where it's connected.
