### ISSUE TITLE
Vertical Marquee

### ISSUE THREAD

**Issue by mackorone** [tidbyt/pixlet#18]
I'd love the ability to scroll paragraphs of text vertically. Context: I'm working on a "Word of the Day" app and often there's not enough room to fit the definition. A horizontal marquee is a bit awkward for this use case - I want as much text displayed as possible.

**Comment by juanjramirez** [comment]
Functionality added on #48, if you want to test it before release you can follow the steps on [BUILD.md](https://github.com/tidbyt/pixlet/blob/main/BUILD.md)

**Comment by betterengineering** [comment]
Thanks for the update @juanjramirez! So sorry for the delay here. Closing this issue since this functionality exists. @mackorone - let us know if you have any issues with vertical scroll moving forward.
