### ISSUE TITLE
Regex capture group support

### ISSUE THREAD

**Issue by mackorone** [tidbyt/pixlet#19]
As far as I can tell, the current regex module doesn't support capture groups. The `search` method simply returns the starting and ending indexes of the entire match - there's no way to get the matched groups. I had to hack around this limitation in one of my recent apps: https://github.com/mackorone/tidbyt-word-of-the-day/blob/main/word_of_the_day.star#L60

Any chance capture groups can be supported?

**Comment by rohansingh** [comment]
Does [`findall`](https://github.com/qri-io/starlib/tree/master/re#findallpattern-text-flags0) do what you need?

**Comment by mackorone** [comment]
As far as I can tell, no:

```
regex = "foo(.*)baz"
content = "foobarbaz"
print(re.findall(regex, content))
```
Output:
```

**Comment by joeyhoer** [comment]
@mackorone Try [`re.match`](https://github.com/qri-io/starlib/blob/master/re/testdata/test.star#L8), it's not documented but it works. It looks like the return value is a tuple, the first item is the full match, and then matching groups follow in order.

**Comment by betterengineering** [comment]
Hi @mackorone - Just tested @joeyhoer's solution and it should do what you're looking for:
```starlark
load("re.star", "re")

def main():
    regex = "foo(.*)baz"
    content = "foobarbaz"
    print(re.match(regex, content))
    return []
```
    
``` bash
$ pixlet render examples/re.star
[examples/re.star] [("foobarbaz", "bar")]
```

It looks like there are a [few methods undocumented](https://github.com/qri-io/starlib/blob/master/re/re.go#L29-L41) and this one of them 😢 

Going to close this for now, thank @joeyhoer for the solution! Please feel free to add a comment or open a new issue if this doesn't solve your use case.
