### ISSUE TITLE
The time on the clock example is static (it doesn't change with time!)

### ISSUE THREAD

**Issue by jimzenn** [tidbyt/pixlet#219]
I served the clock example, and noticed that the time on the clock is static: it remains at the time when you run the pixlet, but it doesn't change as time goes by.

Hey! That's not a real clock! 🧐

**Comment by MKLOL** [comment]
Yeah same issue here, wanted to write a custom app that has clock + some custom info from external apis, but on the tidbyt (and in the dev environment) it's not updating. What's the fix ?

**Comment by rs7q5** [comment]
When developing if you run `pixlet serve --watch <app>`  it should update accordingly worst case if you refresh the local host it should update.

**Comment by jimzenn** [comment]
Does this mean for a clock to work, it has to interact with Tidbyt server?
 🤔 I think if Tidbyt can interact with servers, it should have enough
packages to update clocks on its own. Still, it is somewhat hard to believe
that it can’t update the clock gif itself. Am i understanding this
correctly?

**Comment by rs7q5** [comment]
The gifs/webps are static so you have to rerun the scripts to update the images. The script is just being rerun on their end to update the clock image.

It does not update any of the gifs without rerunning scripts from my understanding.
