### ISSUE TITLE
Questions regarding max_age and temporarily not displaying an app

### ISSUE THREAD

**Issue by TiiFuchs** [tidbyt/pixlet#228]
Regarding the max_age option (see #143):
The max_age option does only work in combination with your backend server, doesn't it? So it's not handled on the device itself?
Is there a way to mimic this behaviour when pushing an app via the `pixlet push` command?

And how does an app need to be rendered to skip it? Like you did with the "only on game day" option for the NFL app...?

**Comment by matslina** [comment]
Hey @TiiFuchs.

Both `max_age` and "skipping" currently only works when an applet runs on our servers, and for both we'd like to make it possible to achieve the same via the API. Not quite there yet though!

When running in our env, if an applet's `main()` returns an empty list, the app will be skipped in the rotation.
