### ISSUE TITLE
Sequence widget unavailable in v0.17.6

### ISSUE THREAD

**Issue by aschechter88** [tidbyt/pixlet#282]
`Error: module has no .Sequence field or method`

The Sequence widget isn't making into the module exports. From debug:

```
[onebusaway2.star] ["Animation", "Box", "Circle", "Column", "Image", "Marquee", "Padding", "Plot", "Root", "Row", "Stack", "Text", "WrappedText", "fonts"]
2022/05/19 13:56:14 error loading applet: error running script: Traceback (most recent call last):
  onebusaway2.star:39:22: in main
Error: module has no .Sequence field or method
^C
$ pixlet version
Pixlet version: v0.17.6
```

**Comment by rs7q5** [comment]
You can clone the full repo and build there and it is useable that way. 

I suspect they'll build it into the next release though. 

But that's what you can do if you don't want to wait.

**Comment by rs7q5** [comment]
It did that when it was merged since the changes to the docs and the inclusion of the code to perform it was part of the same PR. 

I can say though if you just build it from the source and not just unpack the binary it does work.

**Comment by rs7q5** [comment]
Looks like they update the release build so 'render.Sequence` should be available!!
