### ISSUE TITLE
Support for UTF8 text

### ISSUE THREAD

**Issue by thejeshgn** [tidbyt/pixlet#37]
Will be useful for people outside English speaking countries.

**Comment by betterengineering** [comment]
Hey @thejeshgn! So sorry for the delay. Pixlet should be able to support UTF-8 out of the box, can you provide more details on what you're trying to do? One thing to note, not all fonts contain all glyphs, so even if we do support UTF-8, we may not have a font that suits the language you are trying to use. If that's the case, feel free to submit a PR adding a font to fit your use case! If there are bugs supporting UTF-8, please feel free to follow up on this issue so we can take a closer look.

**Comment by betterengineering** [comment]
As an update - we chatted a few times internally over the last few months on how to best support internationalized fonts with Pixlet. Sourcing small, BDF fonts that look good on a Tidbyt in a language we can't read natively is pretty challenging. Even if we found a nice font that supported a target character set, we wouldn't be able to validate it displays correctly at 5-8 pixels. Adding more languages to the device is on our roadmap but it's not something we can prioritize in the short term.

We overly welcome community support here. If there is a language you want to see on your Tidbyt and are willing to help us validate it looks good, please open an issue with the specific language you are looking for. We can take on the technical work if someone is willing to help us validate the character set on the display.
