### ISSUE TITLE
Support/document installation on ARM

### ISSUE THREAD

**Issue by rohansingh** [tidbyt/pixlet#38]
We've gotten a couple requests now from users with `arm` and `arm64` (Raspberry Pi, Apple M1). The main sticking point seems to be WebP. The library is fairly portable and some users have even managed to install `libwebp`, but Pixlet still doesn't seem to build.

- [x] Investigate & resolve blockers for ARM installations.
- [x] Document how to install on Raspberry Pi.
- [x] Document how to install on M1.

**Comment by noktulo** [comment]
Any idea when this might be worked out? I preordered and was excited to get started on building my app but can't as I have an M1. For reference, this is the issue I'm getting:

`Cloning into '/opt/homebrew/Library/Taps/tidbyt/homebrew-tidbyt'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 43 (delta 25), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (43/43), 6.53 KiB | 2.18 MiB/s, done.
Resolving deltas: 100% (25/25), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/tidbyt/homebrew-tidbyt/pixlet.rb
formulae require at least a URL
Error: Cannot tap tidbyt/tidbyt: invalid syntax in tap!
`

**Comment by antonym** [comment]
See https://github.com/tidbyt/pixlet/issues/39 for a workaround.

**Comment by TheJizel** [comment]
FWIW, I was able to install on a Raspberry Pi 4 without much issue. Here are the steps I took:

1. Follow the "How to Install Go on the Raspberry Pi" tutorial [here](https://www.jeremymorgan.com/tutorials/raspberry-pi/install-go-raspberry-pi/) to install `go`. I am running the 64-bit version of Raspbian / Raspberry Pi OS (which, for reference, can be found [here](https://downloads.raspberrypi.org/raspios_arm64/images/)), so I downloaded the latest stable version on the ARM64 architecture for Linux as part of step 1.
2. Ran `apt update` then `apt install git libwebp-dev -y` to install `libwebp`.
3. Followed the "Steps" section from [`BUILD.md`](https://github.com/tidbyt/pixlet/blob/main/BUILD.md) to install `pixlet`.
4. _(optional)_ Moved the `pixlet` binary to `/usr/local/bin` (which is in my `PATH`).

**Comment by betterengineering** [comment]
Hi folks! A few updates here.
- #93 adds support for cross-compiling for ARM64 for both MacOS and Linux. We still need to get our build system updated internally to be able to run those scripts.
- #81 adds support to our goreleaser config to be able to release those binaries. We're just waiting on our build system updates before landing.
- Installation instructions are the same for both CPU architectures for the respective platforms. MacOS installations will be able to be installed through Homebrew as usual and Linux installations will be able to be installed through downloading the binary and putting it in your path.

**Comment by betterengineering** [comment]
We found one more change we needed: #104 to fix the release. I originally thought we would update our internal release, but it feels much better to get all of the release process into this repo so we can make changes in one shot in the future.

**Comment by betterengineering** [comment]
Pixlet version [v0.8.4](https://github.com/tidbyt/pixlet/releases/tag/v0.8.4) now has Apple M1 and Linux ARM64 support! We've tested through Homebrew on an Apple M1 and we've tested through curl + tar on a Raspberry Pi V4.

**Comment by samandmoore** [comment]
works great for me. thanks @betterengineering 🤙🏻

**Comment by betterengineering** [comment]
Thank _you_ @samandmoore!
