### ISSUE TITLE
Starlib Time Update

### ISSUE THREAD

**Issue by joeyhoer** [tidbyt/pixlet#42]
The README correctly statues that time operations have been upstreamed into starlark-go, but unless I am mistaken, this is not reflected in the actual build. 

For example, calling [the `parseTime` (or `parse_time`) method](https://github.com/google/starlark-go/blob/master/lib/time/time.go#L91) from a Pixlet app results in the following error:

```
Error: module has no .parseTime field or method
```

However, calling [the older `time` method](https://github.com/qri-io/starlib/blob/v0.4.2/time/time.go#L105) appears to work.

Am I doing something wrong? Is think likely to change in a future release?

**Comment by betterengineering** [comment]
Hey @joeyhoer - so sorry for the delay. This should be resolved by the version bump of starlib in #46. I'll cut a release with these changes by EOD.
