### ISSUE TITLE
Pls help with install process on windows

### ISSUE THREAD

**Issue by 22dalarbi** [tidbyt/pixlet#451]
I followed all the steps and it works until I get to "make build". No matter how much I have tried it keeps saying:

$ make build
-bash: make: command not found

Someone pls help me, this is so stupid I'm losing my mind over it. Also, I have already tried re-installing everything.

**Comment by jmshelton12800** [comment]
Same, I have a file that reads pixlet and has all the items listed on github, but I'm not seeing a .exe in there or how to copy it over to the path.

I am new to programming, please don't shame me if I already have everything I need, just trying to figure it out myself.

**Comment by 22dalarbi** [comment]
> Same, I have a file that reads pixlet and has all the items listed on github, but I'm not seeing a .exe in there or how to copy it over to the path.
> 
> I am new to programming, please don't shame me if I already have everything I need, just trying to figure it out myself.

I figured it out you have to use this command: (in mingw64) PATH=$PATH:/c/msys64/home/michael/pixlet but replacing micheal with your name or whatever that folder name is (just follow the path to figure out). Then you have to open the command prompt on windows and type in: cd c:\msys64\home\micheal\pixlet, (once again replacing micheal with ur folder name). Then to test out the examples they give run the command: pixlet serve --watch example/hello_world.star
This is an example, but you can replace that file name with any of the examples in the folder, (which is in the pixlet folder) Hopes this helps, I got this help from the discord.

**Comment by betterengineering** [comment]
Hey folks! So sorry for the Windows pain points. We now have an official Windows release as of [v0.22.4](https://github.com/tidbyt/pixlet/releases/tag/v0.22.4) :tada: . To get started, follow the [installation instructions](https://tidbyt.dev/docs/build/installing-pixlet#install-on-windows) for windows. I'm going to leave this issue open for a bit, let me know if you run into any issues in a comment to this issue.

**Comment by cbejar93** [comment]
I'm also having issues with running it on Windows. I've followed the instructions and have a pixlet folder like this:

![image](https://user-images.githubusercontent.com/35776711/201450038-44b533e8-208c-4e3c-911e-792ad2dc3229.png)

In the env variables I have it like this:

![image](https://user-images.githubusercontent.com/35776711/201450108-4fdc2f63-37a2-4f25-8044-6a1ec57e3cf5.png)


I try running pixlet serve in the powershell, but I get command not found error.
Any help would be appreciated.

**Comment by LukiLeu** [comment]
It looks like you downloaded the source code instead of the binary. You need to download and extract the pixlet_0.22.6_windows_amd64.tar.gz file.
