### ISSUE TITLE
0.22.8 glibc issue

### ISSUE THREAD

**Issue by krismolendyke** [tidbyt/pixlet#521]
Looks like #514 introduced a regression in the Linux binary distribution:

```
pixlet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by pixlet)
pixlet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pixlet)
```

Downgrading to `0.22.7` works for me.

**Comment by elyscape** [comment]
I'm experiencing this as well on Raspberry Pi OS, which is based on Debian Bullseye:
```shellsession
$ pixlet --help
pixlet: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by pixlet)
pixlet: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pixlet)
```
Debian Bullseye uses libc version 2.31.

**Comment by elyscape** [comment]
Pinging @betterengineering for visibility.

**Comment by joshspicer** [comment]
+1 Seeing this on linux (GitHub Codespaces with the `go` image `mcr.microsoft.com/devcontainers/go`

**Comment by Matt-Pesce** [comment]
I had this GLIBC error message as well (downloaded pixlet binary version 0.22.8).  My system shows version 2.31 which is also declared as latest package when I try to upgrade (Ubuntu GLIBC 2.31-0ubuntu9.9) running Ubuntu 20.04.   Rebuild of pixlet 0.22.8 from source solved the problem, however caused a fair bit of pain in the process as I had to update Node, npm, Go as I was previously on Pixlet version 17.

**Comment by betterengineering** [comment]
He folks! Sorry about the headaches here. We were statically linking only the libwebp dependency and not everything. I updated this in #559 but only for amd64. In order to get arm64 to also be fully static, I need to spend more time to fix the cross compilation using the appropriate arm based glibc.

**Comment by elyscape** [comment]
Per ipfs/distributions#348 and various other references on the internet (see in particular [this StackOverflow post][stackoverflow]), statically linking glibc can cause issues, and isn't truly static.

The good news is that Zig's C compiler [can be used with CGO][cgo-zig] _and_ has the ability to dynamically link against any version of glibc by specifying the version in the target like so:
```
zig cc -target x86_64-linux-gnu.2.25
zig cc -target aarch64-linux-gnu.2.31
```
I would recommend trying this route instead.

[stackoverflow]: https://stackoverflow.com/a/57478728

[cgo-zig]: https://lucor.dev/post/cross-compile-golang-fyne-project-using-zig/

**Comment by krismolendyke** [comment]
This is working for me now, thanks!

**Comment by elyscape** [comment]
This is still happening for me on arm64.
