### ISSUE TITLE
"encrypt" command will not work with secrets prefixed by "-" character

### ISSUE THREAD

**Issue by alecspringel** [tidbyt/pixlet#705]
This issue may be better suited for the [Cobra CLI library](https://github.com/spf13/cobra), but I figured it should be noted here as well 😃 

**Summary of the issue:**
Some OAuth implementations contain client IDs and secrets that begin with a "-" character. When running `pixlet encrypt` on a secret that begin with a "-", the character is confused for a flag.

**How to reproduce:**
Running `pixlet encrypt <app_name> -secret_that_starts_with_a_dash`

Yields the response:
`Error: unknown shorthand flag: 's' in -secret_that_starts_with_a_dash`

I was able to get around this by creating a new app which generated a new Client ID, but that may not always be an option.

**Comment by westy92** [comment]
I was able to get it to run by putting quotes around my key, but I'm not sure if it encrypted correctly.

**Comment by rohansingh** [comment]
This is a shell syntax issue. Quotes work as @westy92 pointed out. Alternatively [`--`][1] should work:

```bash
pixlet encrypt -- my_app -some-secret
```

[1]: https://unix.stackexchange.com/questions/11376/what-does-double-dash-double-hyphen-mean

**Comment by rohansingh** [comment]
This is a shell syntax issue. Quotes work as @westy92 pointed out. Alternatively [`--`][1] should work:

```bash
pixlet encrypt -- my_app -some-secret
```

[1]: https://unix.stackexchange.com/questions/11376/what-does-double-dash-double-hyphen-mean
