### ISSUE TITLE
Error with Build Docs 

### ISSUE THREAD

**Issue by tget4** [tidbyt/pixlet#84]
The latest change to the docs in Build.MD don't seem to work for me.

![image](https://user-images.githubusercontent.com/3528324/147135670-44b1b08a-10ff-4ef6-b1cb-8dee6ce2b20a.png)

Using relative paths and an out directory seems to work though.

```
go build -o ./out  ./render ./runtime ./encode .
```

**Comment by paulsavage** [comment]
I've tried this on OSX Monterey 12.0 and that didn't run. A binary for **darwin/arm64** would be great.

**Comment by betterengineering** [comment]
Hey @tget4 - thanks for the issue! I noticed we have quite a few ways to build this repo 😅 . I've created a PR to clean it up.

**Comment by betterengineering** [comment]
Hey @paulsavage - so sorry about that. We have #38, #39 are currently open to track the issue and #81 should resolve the issue once confirmed.
