### ISSUE TITLE
`brew install`: invalid syntax in tap

### ISSUE THREAD

**Issue by jazzdan** [tidbyt/pixlet#88]
Output of `brew install`:

```
brew install tidbyt/tidbyt/pixlet
==> Tapping tidbyt/tidbyt
Cloning into '/opt/homebrew/Library/Taps/tidbyt/homebrew-tidbyt'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 67 (delta 41), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (67/67), 9.54 KiB | 9.54 MiB/s, done.
Resolving deltas: 100% (41/41), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/tidbyt/homebrew-tidbyt/pixlet.rb
formulae require at least a URL
Error: Cannot tap tidbyt/tidbyt: invalid syntax in tap!
```

Other info that might be helpful:

```
brew doctor
Your system is ready to brew.
```

```
brew config
HOMEBREW_VERSION: 3.3.9-36-ge970bb1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e970bb18765cd4f16c39585cb0eabc9208c68996
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2b69fcaf6cf9925caac56dad26d39d30e89b42c
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.34.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1
Rosetta 2: false
```

**Comment by joelhaasnoot** [comment]
Just ran into this too. It looks like this is because you're on an M1 (Macbook Pro). The file referenced in there error is here https://github.com/tidbyt/homebrew-tidbyt/blob/main/pixlet.rb and it only has definitions/releases for Intel/X86, not ARM

**Comment by joelhaasnoot** [comment]
Also see here https://github.com/tidbyt/pixlet/issues/39#issuecomment-900727783

**Comment by davidgs** [comment]
Came here for this ... guess I'll try building from source and let y'all know how that turns out.

**Comment by joelhaasnoot** [comment]
I was able to get it working. There isn't a straightforward "install" command but it builds/runs fine.

**Comment by jazzdan** [comment]
Yup building and installing works just fine, thank you Go! :)

**Comment by davidgs** [comment]
How did you solve the `go-libwebp` issue? I built and installed that from source, but the build for `pixlet` still wants to use the default.

**Comment by joelhaasnoot** [comment]
Make sure you run the following steps in the same terminal as when you run `make`

 ````export CPATH=/opt/homebrew/include
 export LIBRARY_PATH=/opt/homebrew/lib```

**Comment by betterengineering** [comment]
Hi folks! I'm going to close this issue in favor of #38. As a short term workaround, check out this comment on how to build locally: https://github.com/tidbyt/pixlet/issues/39#issuecomment-900727783

We should have #38 closed out sometime next week.
