### ISSUE TITLE
Push As Installation not working?

### ISSUE THREAD

**Issue by jasondborneman** [tidbyt/pixlet#90]
I'm referencing the Push As Installation instructions: https://github.com/tidbyt/pixlet#push-as-an-installation

Just got my Tidbyt today, and I'm trying to write some code that shows my current lifetime solar power production, etc. When I add an Installation ID to my push command, it never shows up in the app on my phone as that Install ID or anything added by API as the instructions show should happen. 

Here's the commands I'm running in a .sh file that I plan to have update daily from a Raspberry Pi and then I'd like it to show up in my rotation.

```
pixlet render solarlife.star

pixlet push --api-token <API TOKEN> <DEVICE ID> solarlife.webp Solar
```
Also tried it in quotes ("Solar") to no avail.

Is this a known issue?

Thanks!

**Comment by TaylorWh0** [comment]
Hello,

I am having a similar issue and would love help. I am able to push the .webp file and it shows up on the Tidbyt for about 30 seconds and then is gone. It never shows up on the Tidbyt app on my iPhone. I attempted giving it an installation ID in quotes and without quotes. Neither worked. 
Any help would be great, thank you!

**Comment by joeyhoer** [comment]
I had to quit the app on my iPhone and open it back up in order for the Tidbyt app to display within the iPhone app; however, it does display for me, when an `installationID` is passed.

**Comment by TaylorWh0** [comment]
> I had this issue also; but I was able to work around it by quitting the iPhone app, and then opening it back up. The Tidbyt app will then display within the iPhone app.
> 
> (Make sure you're passing the `installationID` as noted above.)

Thank you for the quick reply. I did kill my iPhone app and it still did not show up. I added "installationID" and then the name of the file, still does not save. It does successfully push one time.

**Comment by jasondborneman** [comment]
Yeah same here, even tried rebooting my phone and the Tidbyt with no luck.

@joeyhoer when you say passing the installation I'd "as noted" what format do you mean? I checked out the code and it should work as long as it's the third argument (after the api key). But maybe I misunderstood

**Comment by magicmq** [comment]
The installationID argument was added in 3588131f8a72aea17d00c0e4a3dee5597c082766, which is after the 0.7.0 release. You'll need to [build the project yourself](https://github.com/tidbyt/pixlet/blob/main/BUILD.md) for it to work.

**Comment by joeyhoer** [comment]
Ah, that makes sense. I did have to build from source, as [the homebrew cask isn’t currently working on M1 macs](https://github.com/tidbyt/pixlet/issues/39#issuecomment-900727783).

**Comment by jasondborneman** [comment]
> The installationID argument was added in [3588131](https://github.com/tidbyt/pixlet/commit/3588131f8a72aea17d00c0e4a3dee5597c082766), which is after the 0.7.0 release. You'll need to [build the project yourself](https://github.com/tidbyt/pixlet/blob/main/BUILD.md) for it to work, or wait until they publish another release.

Gotcha. I should have noticed that when I was looking at the code! Thanks!

**Comment by jasondborneman** [comment]
Building from latest source worked! Thanks, @magicmq!
