### ISSUE TITLE
Open source for existing tidbyt apps

### ISSUE THREAD

**Issue by Eastonco** [tidbyt/pixlet#95]
While this isn't mandatory by any means, it'd be super helpful to release all of the official Tydbit apps available through the app (stocks, Spotify now playing, transit, etc). This would help give developers a better understanding to create more complex apps with non traditional display aspects, things like stock charts and complex layouts. While the [layout documentation](https://github.com/tidbyt/pixlet/blob/main/doc/widgets.md) is good enough, more examples would be greatly appreciated.

**Comment by jasondborneman** [comment]
Seconding and following. I'd love to see this. Would really give more examples of Starlark with complex apps and display.

**Comment by Eastonco** [comment]
Looks like this was actually answered on the [tidbyt forum](https://discuss.tidbyt.com/t/opensourcing-existing-apps/1119/5) a few hours ago

>Hey all, the request definitely makes sense. We’ll discuss as a team here when we’re all back in the office next week.
>
>Some of this is blocked on getting our full app development platform out. For example, with Pixlet you currently can’t specify a configuration schema or accept user configuration values (eg., auth tokens). We have a way to do that for internal apps but need to clean it up and make it public.

**Comment by betterengineering** [comment]
Hey @Eastonco, thanks for the issue! I'm going to close this issue in favor of the discussion post you linked - that way we only have one place to keep up to date on the status of this topic 😅 . Feel free to keep reaching out with new issues if there are more changes you would like to see!
