### ISSUE TITLE
Local deploy to tidbyt - does app refresh?

### ISSUE THREAD

**Issue by mattjones0111** [tidbyt/pixlet#988]
I have a question.

I've created an app and deployed it locally to my tidbyt. I don't think that the app is being refreshed (i.e. that `main()`) is not called) when the app cycles back around.

Is this behaviour expected? Does this change when the app is installed via the app store?

Thanks!

**Comment by Denton-L** [comment]
Yep, this is expected behaviour. And yes, it will rendered properly once it's published to the community repo. See the last paragraph in https://tidbyt.dev/docs/integrate/pushing-apps

> Keep in mind though, the graphic associated with the installation will only change if you push a new one. If you really want to stay up to speed on the price of Bitcoin, you'll have to either keep pushing the graphic, or look into [publishing your app](https://tidbyt.dev/docs/publish/publishing-apps). =)

**Comment by dinosaursrarr** [comment]
This is expected behaviour -- what you pushed to your tidbyt is an image file, not code. The code runs on your machine (or in tidbyt's cloud if published and installed via phone app), so to see something different, you need to re-render and push the new image.
